import {
  Bell,
  BookMarked,
  BookOpen,
  CalendarDays,
  CheckCircle2,
  Clock,
  Database,
  FileArchive,
  FileSpreadsheet,
  GraduationCap,
  LayoutDashboard,
  Link as LinkIcon,
  Megaphone,
  Network,
  UserCircle,
  Settings,
  Users,
} from "lucide-react"

import type { Role } from "../data/portal-data"
import type { ModuleId, NavItem } from "../types/navigation"

export const roleNavigation: Record<Role, NavItem[]> = {
  student: [
    { id: "overview", label: "Home", icon: LayoutDashboard },
    { id: "my-classes", label: "Classes", icon: CalendarDays },
    { id: "grades", label: "Grades & Report", icon: FileSpreadsheet },
    { id: "thesis", label: "Thesis Library", icon: BookOpen },
    { id: "announcements", label: "Announcements", icon: Bell },
    { id: "profile", label: "Profile", icon: UserCircle },
    { id: "availability", label: "Teacher Status", icon: CheckCircle2 },
    { id: "instructors", label: "Instructor Info", icon: Network },
    { id: "cso", label: "CSSO Section", icon: FileArchive },
    { id: "curriculum", label: "Curriculum", icon: GraduationCap },
    { id: "quick-links", label: "Quick Links", icon: LinkIcon },
    { id: "grade-history", label: "Grades Registry", icon: Clock },
  ],
  faculty: [
    { id: "overview", label: "Home", icon: LayoutDashboard },
    { id: "schedule", label: "Class Schedule", icon: CalendarDays },
    { id: "student-roster", label: "Student Roster", icon: BookMarked },
    { id: "thesis", label: "Thesis Library", icon: BookOpen },
    { id: "grades", label: "Grades (Legacy)", icon: FileSpreadsheet },
    { id: "manage-grades", label: "Grade Table", icon: FileSpreadsheet },
    { id: "availability", label: "My Status", icon: CheckCircle2 },
    { id: "instructors", label: "Instructor Info", icon: Network },
    { id: "announcements", label: "Announcements", icon: Bell },
    { id: "cso", label: "CSSO Section", icon: FileArchive },
    { id: "quick-links", label: "Quick Links", icon: LinkIcon },
    { id: "profile", label: "Profile", icon: UserCircle },
  ],
  admin: [
    { id: "overview", label: "Home", icon: LayoutDashboard },
    { id: "profile", label: "Admin Profile", icon: UserCircle },
    { id: "users", label: "User Management", icon: Users },
    { id: "irregular-students", label: "Non-Regular Students", icon: Users },
    { id: "academic", label: "Academic Setup", icon: Settings },
    { id: "classes", label: "Classes", icon: GraduationCap },
    { id: "thesis", label: "Thesis Management", icon: BookMarked },
    { id: "announcements", label: "Announcements", icon: Megaphone },
    { id: "availability", label: "Teacher Status", icon: CheckCircle2 },
    { id: "cso", label: "CSSO Section", icon: FileArchive },
    { id: "audit", label: "Audit Logs", icon: Database },
    { id: "quick-links", label: "Quick Links", icon: LinkIcon },
  ],
  csso_officer: [
    { id: "overview", label: "Home", icon: LayoutDashboard },
    { id: "cso", label: "CSSO Section", icon: FileArchive },
    { id: "thesis", label: "Thesis Library", icon: BookOpen },
    { id: "announcements", label: "Announcements", icon: Bell },
    { id: "profile", label: "Profile", icon: UserCircle },
    { id: "quick-links", label: "Quick Links", icon: LinkIcon },
  ],
}

export const initialModule: Record<Role, ModuleId> = {
  student: "overview",
  faculty: "overview",
  admin: "overview",
  csso_officer: "overview",
}
