export const quotes: { text: string; author: string }[] = [
  { text: "The beautiful thing about learning is nobody can take it away from you.", author: "B.B. King" },
  { text: "Education is the most powerful weapon which you can use to change the world.", author: "Nelson Mandela" },
  { text: "The function of education is to teach one to think intensively and to think critically.", author: "Martin Luther King Jr." },
  { text: "Education is not preparation for life; education is life itself.", author: "John Dewey" },
  { text: "The mind is not a vessel to be filled, but a fire to be kindled.", author: "Plutarch" },
  { text: "The only person who is educated is the one who has learned how to learn and change.", author: "Carl Rogers" },
  { text: "I cannot teach anybody anything, I can only make them think.", author: "Socrates" },
  { text: "The only true wisdom is in knowing you know nothing.", author: "Socrates" },
  { text: "Wonder is the beginning of wisdom.", author: "Socrates" },
  { text: "Education is the kindling of a flame, not the filling of a vessel.", author: "Socrates" },
  { text: "The unexamined life is not worth living.", author: "Socrates" },
  { text: "Knowledge of the soul is the beginning of wisdom.", author: "Socrates" },
  { text: "I know that I am intelligent because I know that I know nothing.", author: "Socrates" },
  { text: "To know is to know that you know nothing. That is the meaning of true knowledge.", author: "Socrates" },
  { text: "Employ your time in improving yourself by other men's writings, so that you shall gain easily what others have labored hard for.", author: "Socrates" },
  { text: "The beginning of wisdom is a definition of terms.", author: "Socrates" },
  { text: "True knowledge exists in knowing that you know nothing.", author: "Socrates" },
  { text: "It is not living that matters, but living rightly.", author: "Socrates" },
  { text: "The greatest way to live with honor in this world is to be what we pretend to be.", author: "Socrates" },
  { text: "Be kind, for everyone you meet is fighting a hard battle.", author: "Socrates" },
  { text: "Wisdom begins in wonder.", author: "Socrates" },
  { text: "The noblest of all studies is the study of what man should be and what he should pursue.", author: "Socrates" },
  { text: "True wisdom comes to each of us when we realize how little we understand about life, ourselves, and the world around us.", author: "Socrates" },
  { text: "He who is not a good servant will not be a good master.", author: "Plato" },
  { text: "The measure of a man is what he does with power.", author: "Plato" },
  { text: "Thinking: the talking of the soul with itself.", author: "Plato" },
  { text: "The direction in which education starts a man will determine his future life.", author: "Plato" },
  { text: "Do not train a child to learn by force or harshness; but direct them to it by what amuses their minds.", author: "Plato" },
  { text: "Necessity is the mother of invention.", author: "Plato" },
  { text: "Knowledge which is acquired under compulsion obtains no hold on the mind.", author: "Plato" },
  { text: "The soul of man is immortal and imperishable.", author: "Plato" },
  { text: "A good decision is based on knowledge and not on numbers.", author: "Plato" },
  { text: "Ideas are the source of all things.", author: "Plato" },
  { text: "The learning and knowledge that we have, is, at the most, but little compared with that of which we are ignorant.", author: "Plato" },
  { text: "Courage is knowing what not to fear.", author: "Plato" },
  { text: "Ignorance, the root and stem of all evil.", author: "Plato" },
  { text: "Man is a being in search of meaning.", author: "Plato" },
  { text: "Science is nothing but perception.", author: "Plato" },
  { text: "The roots of education are bitter, but the fruit is sweet.", author: "Aristotle" },
  { text: "It is the mark of an educated mind to be able to entertain a thought without accepting it.", author: "Aristotle" },
  { text: "Educating the mind without educating the heart is no education at all.", author: "Aristotle" },
  { text: "Excellence is never an accident. It is always the result of high intention, sincere effort, and intelligent execution.", author: "Aristotle" },
  { text: "We are what we repeatedly do. Excellence, then, is not an act, but a habit.", author: "Aristotle" },
  { text: "The more you know, the more you realize you don't know.", author: "Aristotle" },
  { text: "Pleasure in the job puts perfection in the work.", author: "Aristotle" },
  { text: "To know oneself is the beginning of all wisdom.", author: "Aristotle" },
  { text: "All men by nature desire to know.", author: "Aristotle" },
  { text: "It is during our darkest moments that we must focus to see the light.", author: "Aristotle" },
  { text: "Patience is bitter, but its fruit is sweet.", author: "Aristotle" },
  { text: "Knowing yourself is the beginning of all wisdom.", author: "Aristotle" },
  { text: "No great mind has ever existed without a touch of madness.", author: "Aristotle" },
  { text: "The educated differ from the uneducated as much as the living differ from the dead.", author: "Aristotle" },
  { text: "Happiness depends upon ourselves.", author: "Aristotle" },
  { text: "What is a friend? A single soul dwelling in two bodies.", author: "Aristotle" },
  { text: "Wishing to be friends is quick work, but friendship is a slow ripening fruit.", author: "Aristotle" },
  { text: "The whole is more than the sum of its parts.", author: "Aristotle" },
  { text: "Quality is not an act, it is a habit.", author: "Aristotle" },
  { text: "Those who educate children well are more to be honored than they who produce them.", author: "Aristotle" },
  { text: "Tell me and I forget. Teach me and I remember. Involve me and I learn.", author: "Benjamin Franklin" },
  { text: "An investment in knowledge pays the best interest.", author: "Benjamin Franklin" },
  { text: "Well done is better than well said.", author: "Benjamin Franklin" },
  { text: "Diligence is the mother of good luck.", author: "Benjamin Franklin" },
  { text: "Being ignorant is not so much a shame, as being unwilling to learn.", author: "Benjamin Franklin" },
  { text: "Lost time is never found again.", author: "Benjamin Franklin" },
  { text: "The doors of wisdom are never shut.", author: "Benjamin Franklin" },
  { text: "Without continual growth and progress, such words as improvement, achievement, and success have no meaning.", author: "Benjamin Franklin" },
  { text: "Hide not your talents, they for use were made. What's a sundial in the shade?", author: "Benjamin Franklin" },
  { text: "A learned blockhead is a greater blockhead than an ignorant one.", author: "Benjamin Franklin" },
  { text: "He that can have patience can have what he will.", author: "Benjamin Franklin" },
  { text: "Wise men don't need advice. Fools won't take it.", author: "Benjamin Franklin" },
  { text: "A man wrapped up in himself makes a very small bundle.", author: "Benjamin Franklin" },
  { text: "Reading makes a full man, meditation a profound man, discourse a clear man.", author: "Benjamin Franklin" },
  { text: "He who learns but does not think is lost. He who thinks but does not learn is in great danger.", author: "Confucius" },
  { text: "Study the past if you would define the future.", author: "Confucius" },
  { text: "The man who asks a question is a fool for a minute, the man who does not ask is a fool for life.", author: "Confucius" },
  { text: "Learning without thought is labor lost; thought without learning is perilous.", author: "Confucius" },
  { text: "Choose a job you love, and you will never have to work a day in your life.", author: "Confucius" },
  { text: "Wherever you go, go with all your heart.", author: "Confucius" },
  { text: "Everything has beauty, but not everyone sees it.", author: "Confucius" },
  { text: "When you see a good person, think of becoming like them. When you see someone not so good, reflect on your own weak points.", author: "Confucius" },
  { text: "Real knowledge is to know the extent of one's ignorance.", author: "Confucius" },
  { text: "They must often change who would be constant in happiness or wisdom.", author: "Confucius" },
  { text: "Our greatest glory is not in never falling, but in rising every time we fall.", author: "Confucius" },
  { text: "I hear and I forget. I see and I remember. I do and I understand.", author: "Confucius" },
  { text: "It does not matter how slowly you go as long as you do not stop.", author: "Confucius" },
  { text: "To know what you know and what you do not know, that is true knowledge.", author: "Confucius" },
  { text: "The will to win, the desire to succeed, the urge to reach your full potential — these are the keys that will unlock the door to personal excellence.", author: "Confucius" },
  { text: "If you think in terms of a year, plant a seed; if in terms of ten years, plant trees; if in terms of 100 years, teach the people.", author: "Confucius" },
  { text: "You cannot open a book without learning something.", author: "Confucius" },
  { text: "A superior man is modest in his speech, but exceeds in his actions.", author: "Confucius" },
  { text: "Better a diamond with a flaw than a pebble without.", author: "Confucius" },
  { text: "When anger rises, think of the consequences.", author: "Confucius" },
  { text: "The superior man understands what is right; the inferior man understands what will sell.", author: "Confucius" },
  { text: "Life is really simple, but we insist on making it complicated.", author: "Confucius" },
  { text: "Wisdom, compassion, and courage are the three universally recognized moral qualities of men.", author: "Confucius" },
  { text: "Education breeds confidence. Confidence breeds hope. Hope breeds peace.", author: "Confucius" },
  { text: "Learn as if you will live forever, live as if you will die tomorrow.", author: "Mahatma Gandhi" },
  { text: "Live as if you were to die tomorrow. Learn as if you were to live forever.", author: "Mahatma Gandhi" },
  { text: "The best way to find yourself is to lose yourself in the service of others.", author: "Mahatma Gandhi" },
  { text: "An eye for an eye only ends up making the whole world blind.", author: "Mahatma Gandhi" },
  { text: "Happiness is when what you think, what you say, and what you do are in harmony.", author: "Mahatma Gandhi" },
  { text: "Strength does not come from physical capacity. It comes from an indomitable will.", author: "Mahatma Gandhi" },
  { text: "A man is but the product of his thoughts. What he thinks, he becomes.", author: "Mahatma Gandhi" },
  { text: "The future depends on what you do today.", author: "Mahatma Gandhi" },
  { text: "The best education consists not only in acquiring knowledge but in developing character.", author: "Mahatma Gandhi" },
  { text: "By education I mean an all-round drawing of the best in man and woman in body, mind and spirit.", author: "Mahatma Gandhi" },
  { text: "Literacy in itself is no education. Literacy is not the end of education or even the beginning.", author: "Mahatma Gandhi" },
  { text: "Education should be so revolutionized as to answer the wants of the poorest villager.", author: "Mahatma Gandhi" },
  { text: "Character is formed more powerfully by the environment than by direct instruction.", author: "Mahatma Gandhi" },
  { text: "The aim of university education should be to turn out true servants of the people.", author: "Mahatma Gandhi" },
  { text: "Intelligence plus character — that is the goal of true education.", author: "Martin Luther King Jr." },
  { text: "The function of education, therefore, is to teach one to think intensively and to think critically.", author: "Martin Luther King Jr." },
  { text: "Darkness cannot drive out darkness; only light can do that. Hate cannot drive out hate; only love can do that.", author: "Martin Luther King Jr." },
  { text: "The time is always right to do what is right.", author: "Martin Luther King Jr." },
  { text: "Faith is taking the first step even when you don't see the whole staircase.", author: "Martin Luther King Jr." },
  { text: "The ultimate measure of a man is not where he stands in moments of comfort and convenience, but where he stands at times of challenge and controversy.", author: "Martin Luther King Jr." },
  { text: "Every man must decide whether he will walk in the light of creative altruism or in the darkness of destructive selfishness.", author: "Martin Luther King Jr." },
  { text: "We must build dikes of courage to hold back the flood of fear.", author: "Martin Luther King Jr." },
  { text: "Intelligence is not enough. Intelligence plus character, that is the goal of true education.", author: "Martin Luther King Jr." },
  { text: "Science investigates; religion interprets. Science gives man knowledge, which is power; religion gives man wisdom, which is control.", author: "Martin Luther King Jr." },
  { text: "The purpose of education is to create in a person the ability to look at the world for themselves.", author: "Martin Luther King Jr." },
  { text: "I have the audacity to believe that peoples everywhere can have three meals a day for their bodies, education and culture for their minds.", author: "Martin Luther King Jr." },
  { text: "The function of education is to teach one to think intensively and to think critically. Intelligence plus character — that is the goal of true education.", author: "Martin Luther King Jr." },
  { text: "Education is the passport to the future, for tomorrow belongs to those who prepare for it today.", author: "Malcolm X" },
  { text: "Without education, you're not going anywhere in this world.", author: "Malcolm X" },
  { text: "A man who stands for nothing will fall for anything.", author: "Malcolm X" },
  { text: "If you're not careful, the newspapers will have you hating the people who are being oppressed, and loving the people who are doing the oppressing.", author: "Malcolm X" },
  { text: "I have never let my schooling interfere with my education.", author: "Mark Twain" },
  { text: "The man who does not read has no advantage over the man who cannot read.", author: "Mark Twain" },
  { text: "Keep away from people who try to belittle your ambitions. Small people always do that, but the really great make you feel that you, too, can become great.", author: "Mark Twain" },
  { text: "The secret of getting ahead is getting started.", author: "Mark Twain" },
  { text: "Never let formal education get in the way of your learning.", author: "Mark Twain" },
  { text: "I have never let my schooling interfere with my education.", author: "Mark Twain" },
  { text: "It's not the size of the dog in the fight, it's the size of the fight in the dog.", author: "Mark Twain" },
  { text: "Don't let schooling interfere with your education.", author: "Mark Twain" },
  { text: "Courage is resistance to fear, mastery of fear — not absence of fear.", author: "Mark Twain" },
  { text: "Education consists mainly of what we have unlearned.", author: "Mark Twain" },
  { text: "So many books, so little time.", author: "Frank Zappa" },
  { text: "A room without books is like a body without a soul.", author: "Marcus Tullius Cicero" },
  { text: "If you have a garden and a library, you have everything you need.", author: "Marcus Tullius Cicero" },
  { text: "The pursuit of knowledge can never be achieved without curiosity.", author: "Marcus Tullius Cicero" },
  { text: "Gratitude is not only the greatest of virtues, but the parent of all others.", author: "Marcus Tullius Cicero" },
  { text: "The more we know, the more we realize we don't know.", author: "Marcus Tullius Cicero" },
  { text: "Silence is one of the great arts of conversation.", author: "Marcus Tullius Cicero" },
  { text: "A mind without instruction can no more bear fruit than can a field without cultivation.", author: "Marcus Tullius Cicero" },
  { text: "What we learn with pleasure we never forget.", author: "Alfred Mercier" },
  { text: "Knowledge is power.", author: "Francis Bacon" },
  { text: "Reading makes a full man; conference a ready man; and writing an exact man.", author: "Francis Bacon" },
  { text: "Knowledge is power, but enthusiasm pulls the switch.", author: "Francis Bacon" },
  { text: "Some books are to be tasted, others to be swallowed, and some few to be chewed and digested.", author: "Francis Bacon" },
  { text: "The reading of all good books is like a conversation with the finest minds of past centuries.", author: "René Descartes" },
  { text: "I think, therefore I am.", author: "René Descartes" },
  { text: "Doubt is the origin of wisdom.", author: "René Descartes" },
  { text: "The greatest minds are capable of the greatest vices as well as the greatest virtues.", author: "René Descartes" },
  { text: "Divide each difficulty into as many parts as is feasible and necessary to resolve it.", author: "René Descartes" },
  { text: "It is not enough to have a good mind; the main thing is to use it well.", author: "René Descartes" },
  { text: "The reading of all good books is like a conversation with the finest minds of past centuries.", author: "René Descartes" },
  { text: "If you would be a real seeker after truth, it is necessary that at least once in your life you doubt, as far as possible, all things.", author: "René Descartes" },
  { text: "The first step to knowledge is to know that we are ignorant.", author: "René Descartes" },
  { text: "Intelligence is the ability to adapt to change.", author: "Stephen Hawking" },
  { text: "However difficult life may seem, there is always something you can do and succeed at.", author: "Stephen Hawking" },
  { text: "The greatest enemy of knowledge is not ignorance, it is the illusion of knowledge.", author: "Stephen Hawking" },
  { text: "Look up at the stars and not down at your feet. Try to make sense of what you see and wonder about what makes the universe exist.", author: "Stephen Hawking" },
  { text: "We are just an advanced breed of monkeys on a minor planet of a very average star. But we can understand the universe. That makes us something very special.", author: "Stephen Hawking" },
  { text: "Education is not the learning of facts, but the training of the mind to think.", author: "Albert Einstein" },
  { text: "Imagination is more important than knowledge.", author: "Albert Einstein" },
  { text: "The important thing is not to stop questioning. Curiosity has its own reason for existing.", author: "Albert Einstein" },
  { text: "Anyone who has never made a mistake has never tried anything new.", author: "Albert Einstein" },
  { text: "I have no special talent. I am only passionately curious.", author: "Albert Einstein" },
  { text: "Wisdom is not a product of schooling but of the lifelong attempt to acquire it.", author: "Albert Einstein" },
  { text: "Learn from yesterday, live for today, hope for tomorrow.", author: "Albert Einstein" },
  { text: "Once you stop learning, you start dying.", author: "Albert Einstein" },
  { text: "Only a life lived for others is a life worthwhile.", author: "Albert Einstein" },
  { text: "Strive not to be a success, but rather to be of value.", author: "Albert Einstein" },
  { text: "The only source of knowledge is experience.", author: "Albert Einstein" },
  { text: "Try not to become a man of success, but rather try to become a man of value.", author: "Albert Einstein" },
  { text: "We cannot solve our problems with the same thinking we used when we created them.", author: "Albert Einstein" },
  { text: "Life is like riding a bicycle. To keep your balance, you must keep moving.", author: "Albert Einstein" },
  { text: "The value of a college education is not the learning of many facts but the training of the mind to think.", author: "Albert Einstein" },
  { text: "I am enough of an artist to draw freely upon my imagination. Imagination is more important than knowledge.", author: "Albert Einstein" },
  { text: "The measure of intelligence is the ability to change.", author: "Albert Einstein" },
  { text: "Education is what remains after one has forgotten what one has learned in school.", author: "Albert Einstein" },
  { text: "It is the supreme art of the teacher to awaken joy in creative expression and knowledge.", author: "Albert Einstein" },
  { text: "A person who never made a mistake never tried anything new.", author: "Albert Einstein" },
  { text: "The true sign of intelligence is not knowledge but imagination.", author: "Albert Einstein" },
  { text: "The aim of education is the knowledge not of fact, but of values.", author: "William S. Burroughs" },
  { text: "A teacher affects eternity; he can never tell where his influence stops.", author: "Henry Adams" },
  { text: "They know enough who know how to learn.", author: "Henry Adams" },
  { text: "The goal of education is the advancement of knowledge and the dissemination of truth.", author: "John F. Kennedy" },
  { text: "A child miseducated is a child lost.", author: "John F. Kennedy" },
  { text: "The human mind is our fundamental resource.", author: "John F. Kennedy" },
  { text: "Leadership and learning are indispensable to each other.", author: "John F. Kennedy" },
  { text: "Let us think of education as the means of developing our greatest abilities.", author: "John F. Kennedy" },
  { text: "The whole purpose of education is to turn mirrors into windows.", author: "Sydney J. Harris" },
  { text: "The great aim of education is not knowledge but action.", author: "Herbert Spencer" },
  { text: "The result of the educative process is capacity for further education.", author: "John Dewey" },
  { text: "Education is not preparation for life; education is life itself.", author: "John Dewey" },
  { text: "We do not learn from experience, we learn from reflecting on experience.", author: "John Dewey" },
  { text: "The school must represent present life — life as real and vital to the child as that which he carries on in the home or in the neighborhood.", author: "John Dewey" },
  { text: "Education is a social process. Education is growth. Education is not a preparation for life; education is life itself.", author: "John Dewey" },
  { text: "The most important attitude that can be formed is that of desire to go on learning.", author: "John Dewey" },
  { text: "I believe that education is the fundamental method of social progress and reform.", author: "John Dewey" },
  { text: "Teaching is the one profession that creates all other professions.", author: "John Dewey" },
  { text: "The aim of education should be to teach us how to think rather than what to think.", author: "John Dewey" },
  { text: "Failure is instructive. The person who really thinks learns quite as much from his failures as from his successes.", author: "John Dewey" },
  { text: "Give the pupils something to do, not something to learn; and the doing is of such a nature as to demand thinking; learning naturally results.", author: "John Dewey" },
  { text: "The self is not something ready-made, but something in continuous formation through choice of action.", author: "John Dewey" },
  { text: "To the unlearned, old age is winter; to the learned, it is harvest season.", author: "The Talmud" },
  { text: "The highest result of education is tolerance.", author: "Helen Keller" },
  { text: "Alone we can do so little; together we can do so much.", author: "Helen Keller" },
  { text: "One can never consent to creep when one feels an impulse to soar.", author: "Helen Keller" },
  { text: "The best and most beautiful things in the world cannot be seen or even touched — they must be felt with the heart.", author: "Helen Keller" },
  { text: "Keep your face to the sunshine and you cannot see a shadow.", author: "Helen Keller" },
  { text: "Optimism is the faith that leads to achievement. Nothing can be done without hope and confidence.", author: "Helen Keller" },
  { text: "What we have once enjoyed we can never lose. All that we love deeply becomes a part of us.", author: "Helen Keller" },
  { text: "Character cannot be developed in ease and quiet. Only through experience of trial and suffering can the soul be strengthened.", author: "Helen Keller" },
  { text: "Walking with a friend in the dark is better than walking alone in the light.", author: "Helen Keller" },
  { text: "The only thing worse than being blind is having sight but no vision.", author: "Helen Keller" },
  { text: "I long to accomplish a great and noble task, but it is my chief duty to accomplish small tasks as if they were great and noble.", author: "Helen Keller" },
  { text: "The best preparation for tomorrow is doing your best today.", author: "H. Jackson Brown Jr." },
  { text: "The secret of success is to know something nobody else knows.", author: "Aristotle Onassis" },
  { text: "I am not a teacher, but an awakener.", author: "Robert Frost" },
  { text: "Education is the ability to listen to almost anything without losing your temper or your self-confidence.", author: "Robert Frost" },
  { text: "Two roads diverged in a wood, and I took the one less traveled by, and that has made all the difference.", author: "Robert Frost" },
  { text: "The only way to get the best of an argument is to avoid it.", author: "Dale Carnegie" },
  { text: "Develop success from failures. Discouragement and failure are two of the surest stepping stones to success.", author: "Dale Carnegie" },
  { text: "One of the most tragic things I know about human nature is that all of us tend to put off living.", author: "Dale Carnegie" },
  { text: "If you want to conquer fear, don't sit home and think about it. Go out and get busy.", author: "Dale Carnegie" },
  { text: "The best way to predict the future is to create it.", author: "Peter Drucker" },
  { text: "Efficiency is doing things right; effectiveness is doing the right things.", author: "Peter Drucker" },
  { text: "Management is doing things right; leadership is doing the right things.", author: "Peter Drucker" },
  { text: "Knowledge must be constantly renewed by ceaseless effort, if it is not to be lost.", author: "Peter Drucker" },
  { text: "The most important thing in communication is to hear what isn't being said.", author: "Peter Drucker" },
  { text: "Learning is a lifelong process of keeping abreast of change.", author: "Peter Drucker" },
  { text: "In learning you will teach, and in teaching you will learn.", author: "Phil Collins" },
  { text: "Never let the future disturb you. You will meet it, if you have to, with the same weapons of reason which today arm you against the present.", author: "Marcus Aurelius" },
  { text: "The happiness of your life depends upon the quality of your thoughts.", author: "Marcus Aurelius" },
  { text: "When you arise in the morning, think of what a precious privilege it is to be alive — to breathe, to think, to enjoy, to love.", author: "Marcus Aurelius" },
  { text: "You have power over your mind — not outside events. Realize this, and you will find strength.", author: "Marcus Aurelius" },
  { text: "The impediment to action advances action. What stands in the way becomes the way.", author: "Marcus Aurelius" },
  { text: "Waste no more time arguing about what a good man should be. Be one.", author: "Marcus Aurelius" },
  { text: "The soul becomes dyed with the color of its thoughts.", author: "Marcus Aurelius" },
  { text: "Very little is needed to make a happy life; it is all within yourself, in your way of thinking.", author: "Marcus Aurelius" },
  { text: "If it is not right, do not do it. If it is not true, do not say it.", author: "Marcus Aurelius" },
  { text: "Everything we hear is an opinion, not a fact. Everything we see is a perspective, not the truth.", author: "Marcus Aurelius" },
  { text: "The best revenge is to be unlike him who performed the injury.", author: "Marcus Aurelius" },
  { text: "Accept the things to which fate binds you, and love the people with whom fate brings you together, but do so with all your heart.", author: "Marcus Aurelius" },
  { text: "Look well into thyself; there is a source of strength which will always spring up if thou wilt always look.", author: "Marcus Aurelius" },
  { text: "The universe is change; our life is what our thoughts make it.", author: "Marcus Aurelius" },
  { text: "He who has a why to live for can bear almost any how.", author: "Friedrich Nietzsche" },
  { text: "Without music, life would be a mistake.", author: "Friedrich Nietzsche" },
  { text: "That which does not kill us makes us stronger.", author: "Friedrich Nietzsche" },
  { text: "He who has a why to live for can bear almost any how.", author: "Friedrich Nietzsche" },
  { text: "One must still have chaos in oneself to be able to give birth to a dancing star.", author: "Friedrich Nietzsche" },
  { text: "The individual has always had to struggle to keep from being overwhelmed by the tribe.", author: "Friedrich Nietzsche" },
  { text: "You have your way. I have my way. As for the right way, the correct way, and the only way, it does not exist.", author: "Friedrich Nietzsche" },
  { text: "To live is to suffer, to survive is to find some meaning in the suffering.", author: "Friedrich Nietzsche" },
  { text: "The higher we soar, the smaller we appear to those who cannot fly.", author: "Friedrich Nietzsche" },
  { text: "All I need is a sheet of paper and something to write with, and then I can turn the world upside down.", author: "Friedrich Nietzsche" },
  { text: "I cannot believe that the inscrutable universe turns on an axis of suffering; surely the strange beauty of the world must somewhere rest on pure joy!", author: "Friedrich Nietzsche" },
  { text: "He who has a strong enough why can bear almost any how.", author: "Friedrich Nietzsche" },
  { text: "We should consider every day lost on which we have not danced at least once.", author: "Friedrich Nietzsche" },
  { text: "The good and the wise are few, but their influence spreads like ripples in water.", author: "Confucius" },
  { text: "He who opens a school door, closes a prison.", author: "Victor Hugo" },
  { text: "To learn to read is to light a fire; every syllable that is spelled out is a spark.", author: "Victor Hugo" },
  { text: "He who does not know one's own history is like a leaf that does not know it is part of a tree.", author: "Victor Hugo" },
  { text: "Intelligence is the wife, imagination is the mistress, memory is the servant.", author: "Victor Hugo" },
  { text: "It is from books that wise people derive consolation in the troubles of life.", author: "Victor Hugo" },
  { text: "The learned man knows that he is ignorant.", author: "Victor Hugo" },
  { text: "The world is a book, and those who do not travel read only a page.", author: "Saint Augustine" },
  { text: "Patience is the companion of wisdom.", author: "Saint Augustine" },
  { text: "The mind commands the body and it obeys. The mind orders itself and it resists.", author: "Saint Augustine" },
  { text: "Knowledge is proud that it knows so much; wisdom is humble that it knows so much.", author: "Saint Augustine" },
  { text: "Seek not to understand that you may believe, but believe that you may understand.", author: "Saint Augustine" },
  { text: "The good man, though a slave, is free; the wicked, though he reigns, is a slave.", author: "Saint Augustine" },
  { text: "The confession of evil works is the first beginning of good works.", author: "Saint Augustine" },
  { text: "We make ourselves a ladder out of our vices if we trample the vices themselves underfoot.", author: "Saint Augustine" },
  { text: "The heart has its reasons which reason knows nothing of.", author: "Blaise Pascal" },
  { text: "All of humanity's problems stem from man's inability to sit quietly in a room alone.", author: "Blaise Pascal" },
  { text: "We are usually convinced more easily by reasons we have found ourselves than by those which have occurred to others.", author: "Blaise Pascal" },
  { text: "Kind words do not cost much. Yet they accomplish much.", author: "Blaise Pascal" },
  { text: "There are two types of minds: the mathematical and the intuitive.", author: "Blaise Pascal" },
  { text: "The greatness of man is great in that he knows himself to be miserable.", author: "Blaise Pascal" },
  { text: "A mere trifle consoles us for a mere trifle distresses us.", author: "Blaise Pascal" },
  { text: "The consciousness of the falsity of present pleasures, and the ignorance of the vanity of absent pleasures, cause inconstancy.", author: "Blaise Pascal" },
  { text: "We like to be deceived, though we know we are being deceived.", author: "Blaise Pascal" },
  { text: "The more intelligent one is, the more men of originality one finds.", author: "Blaise Pascal" },
  { text: "The only shame is to have none.", author: "Blaise Pascal" },
  { text: "In faith there is enough light for those who want to believe and enough shadows to blind those who don't.", author: "Blaise Pascal" },
  { text: "Small minds are concerned with the extraordinary, great minds with the ordinary.", author: "Blaise Pascal" },
  { text: "The duty of the educator is to teach his pupils the dignity of work, the beauty of achievement, and the joy of creation.", author: "Maria Montessori" },
  { text: "The greatest sign of success for a teacher is to be able to say, 'The children are now working as if I did not exist.'", author: "Maria Montessori" },
  { text: "Education is a natural process carried out by the child and is not acquired by listening to words but by experiences in the environment.", author: "Maria Montessori" },
  { text: "Never help a child with a task at which he feels he can succeed.", author: "Maria Montessori" },
  { text: "The development of the child during the first three years after birth is unequalled in intensity and importance.", author: "Maria Montessori" },
  { text: "The first duty of an education is to stir up life, but leave it free to develop.", author: "Maria Montessori" },
  { text: "The goal of early childhood education should be to activate the child's own natural desire to learn.", author: "Maria Montessori" },
  { text: "Free the child's potential and you will transform him into the world.", author: "Maria Montessori" },
  { text: "The child is capable of developing and giving us tangible proof of the possibility of a better humanity.", author: "Maria Montessori" },
  { text: "Early childhood education is the key to the betterment of society.", author: "Maria Montessori" },
  { text: "The needs of mankind are universal. Our means of meeting them create the richness and diversity of the planet.", author: "Margaret Mead" },
  { text: "Children must be taught how to think, not what to think.", author: "Margaret Mead" },
  { text: "Never doubt that a small group of thoughtful, committed citizens can change the world; indeed, it's the only thing that ever has.", author: "Margaret Mead" },
  { text: "The task of the modern educator is not to cut down jungles, but to irrigate deserts.", author: "C.S. Lewis" },
  { text: "You can make anything by writing.", author: "C.S. Lewis" },
  { text: "The very nature of joy makes nonsense of our common distinction between having and wanting.", author: "C.S. Lewis" },
  { text: "A children's story that can only be enjoyed by children is not a good children's story in the slightest.", author: "C.S. Lewis" },
  { text: "The homemaker has the ultimate career. All other careers exist for one purpose only — to support the ultimate career.", author: "C.S. Lewis" },
  { text: "What we learn to do we learn by doing.", author: "Aristotle" },
  { text: "First, have a definite, clear practical ideal — a goal, an objective. Second, have the necessary means to achieve your ends.", author: "Aristotle" },
  { text: "Learning is not child's play; we cannot learn without pain.", author: "Aristotle" },
  { text: "The most useful piece of learning for the uses of life is to unlearn what is untrue.", author: "Antisthenes" },
  { text: "The purpose of learning is growth, and our minds, unlike our bodies, can continue growing as we continue to live.", author: "Mortimer Adler" },
  { text: "The teacher is one who makes himself progressively unnecessary.", author: "Thomas Carruthers" },
  { text: "Learning is not attained by chance; it must be sought for with ardor and attended to with diligence.", author: "Abigail Adams" },
  { text: "The more that you read, the more things you will know. The more that you learn, the more places you'll go.", author: "Dr. Seuss" },
  { text: "You can get help from teachers, but you are going to have to learn a great many things by yourself, sitting alone in a room.", author: "Dr. Seuss" },
  { text: "The mind is not a vessel to be filled but a fire to be kindled.", author: "Plutarch" },
  { text: "The correct analogy for the mind is not a vessel that needs filling, but wood that needs igniting.", author: "Plutarch" },
  { text: "To make no mistakes is not in the power of man; but from their errors and mistakes the wise and good learn wisdom for the future.", author: "Plutarch" },
  { text: "Silence at the proper season is wisdom, and better than any speech.", author: "Plutarch" },
  { text: "Learning is like rowing upstream; not to advance is to drop back.", author: "Chinese Proverb" },
  { text: "A book is like a garden carried in the pocket.", author: "Chinese Proverb" },
  { text: "Teachers open the door, but you must enter by yourself.", author: "Chinese Proverb" },
  { text: "If you are planning for a year, sow rice; if you are planning for a decade, plant trees; if you are planning for a lifetime, educate people.", author: "Chinese Proverb" },
  { text: "Give a man a fish and you feed him for a day; teach a man to fish and you feed him for a lifetime.", author: "Chinese Proverb" },
  { text: "A single conversation with a wise man is better than ten years of study.", author: "Chinese Proverb" },
  { text: "To know the road ahead, ask those coming back.", author: "Chinese Proverb" },
  { text: "I hear, I know. I see, I remember. I do, I understand.", author: "Chinese Proverb" },
  { text: "Learning is a treasure that will follow its owner everywhere.", author: "Chinese Proverb" },
  { text: "A smooth sea never made a skilled sailor.", author: "Proverb" },
  { text: "The noblest pleasure is the joy of understanding.", author: "Leonardo da Vinci" },
  { text: "Simplicity is the ultimate sophistication.", author: "Leonardo da Vinci" },
  { text: "Learning is the only thing the mind never exhausts, never fears, and never regrets.", author: "Leonardo da Vinci" },
  { text: "Study without desire spoils the memory, and it retains nothing that it takes in.", author: "Leonardo da Vinci" },
  { text: "The knowledge of all things is possible.", author: "Leonardo da Vinci" },
  { text: "All our knowledge has its origins in our perceptions.", author: "Leonardo da Vinci" },
  { text: "He who loves practice without theory is like the sailor who boards ship without a rudder and compass and never knows where he may cast.", author: "Leonardo da Vinci" },
  { text: "Iron rusts from disuse; stagnant water loses its purity and in cold weather becomes frozen; even so does inaction sap the vigors of the mind.", author: "Leonardo da Vinci" },
  { text: "I am still learning.", author: "Michelangelo" },
  { text: "Every block of stone has a statue inside it and it is the task of the sculptor to discover it.", author: "Michelangelo" },
  { text: "The greatest danger for most of us is not that our aim is too high and we miss it, but that it is too low and we reach it.", author: "Michelangelo" },
  { text: "If people knew how hard I worked to get my mastery, it wouldn't seem so wonderful at all.", author: "Michelangelo" },
  { text: "A man paints with his brains and not with his hands.", author: "Michelangelo" },
  { text: "The greater danger for most of us lies not in setting our aim too high and falling short, but in setting our aim too low and achieving our mark.", author: "Michelangelo" },
  { text: "Genius is eternal patience.", author: "Michelangelo" },
  { text: "The true work of art is but a shadow of the divine perfection.", author: "Michelangelo" },
  { text: "Every block of stone has a statue inside it, and it is the task of the sculptor to discover it.", author: "Michelangelo" },
  { text: "I saw the angel in the marble and carved until I set him free.", author: "Michelangelo" },
  { text: "If we all did the things we are capable of doing, we would literally astound ourselves.", author: "Thomas Edison" },
  { text: "There is no substitute for hard work.", author: "Thomas Edison" },
  { text: "Many of life's failures are people who did not realize how close they were to success when they gave up.", author: "Thomas Edison" },
  { text: "Opportunity is missed by most people because it is dressed in overalls and looks like work.", author: "Thomas Edison" },
  { text: "Genius is one percent inspiration and ninety-nine percent perspiration.", author: "Thomas Edison" },
  { text: "I have not failed. I've just found 10,000 ways that won't work.", author: "Thomas Edison" },
  { text: "What you are will show in what you do.", author: "Thomas Edison" },
  { text: "Every person, all the events of your life are there because you have drawn them there. What you choose to do with them is up to you.", author: "Richard Bach" },
  { text: "A man's worth is no greater than the worth of his ambitions.", author: "Marcus Aurelius" },
  { text: "The future belongs to those who believe in the beauty of their dreams.", author: "Eleanor Roosevelt" },
  { text: "No one can make you feel inferior without your consent.", author: "Eleanor Roosevelt" },
  { text: "Great minds discuss ideas; average minds discuss events; small minds discuss people.", author: "Eleanor Roosevelt" },
  { text: "Do one thing every day that scares you.", author: "Eleanor Roosevelt" },
  { text: "You must do the thing you think you cannot do.", author: "Eleanor Roosevelt" },
  { text: "Life is what you make it. Always has been, always will be.", author: "Eleanor Roosevelt" },
  { text: "The purpose of life is to live it, to taste experience to the utmost, to reach out eagerly and without fear for newer and richer experience.", author: "Eleanor Roosevelt" },
  { text: "We do not need magic to change the world. We carry all the power we need inside ourselves already.", author: "J.K. Rowling" },
  { text: "It is our choices that show what we truly are, far more than our abilities.", author: "J.K. Rowling" },
  { text: "Failure means a stripping away of the inessential.", author: "J.K. Rowling" },
  { text: "The most important thing is to have a life full of people, and a life full of books.", author: "J.K. Rowling" },
  { text: "Books are the quietest and most constant of friends; they are the most accessible and wisest of counselors, and the most patient of teachers.", author: "Charles W. Eliot" },
  { text: "All the world is a laboratory to the inquiring mind.", author: "Martin H. Fischer" },
  { text: "The only thing that overcomes hard luck is hard work.", author: "Harry Golden" },
  { text: "Success is not final, failure is not fatal: it is the courage to continue that counts.", author: "Winston Churchill" },
  { text: "Courage is what it takes to stand up and speak; courage is also what it takes to sit down and listen.", author: "Winston Churchill" },
  { text: "If you're going through hell, keep going.", author: "Winston Churchill" },
  { text: "Attitude is a little thing that makes a big difference.", author: "Winston Churchill" },
  { text: "Success consists of going from failure to failure without loss of enthusiasm.", author: "Winston Churchill" },
  { text: "The empires of the future are the empires of the mind.", author: "Winston Churchill" },
  { text: "To every man there comes a time in his lifetime when he is called upon to make a decision.", author: "Winston Churchill" },
  { text: "Continuous effort — not strength or intelligence — is the key to unlocking our potential.", author: "Winston Churchill" },
  { text: "Personally I'm always ready to learn, although I do not always like being taught.", author: "Winston Churchill" },
  { text: "The way to see by faith is to shut the eye of reason.", author: "Benjamin Franklin" },
  { text: "To the man who only has a hammer, everything he encounters begins to look like a nail.", author: "Abraham Maslow" },
  { text: "What is necessary to change a person is to change his awareness of himself.", author: "Abraham Maslow" },
  { text: "One can choose to go back toward safety or forward toward growth. Growth must be chosen again and again; fear must be overcome again and again.", author: "Abraham Maslow" },
  { text: "If you deliberately plan on being less than you are capable of being, then I warn you that you'll be unhappy for the rest of your life.", author: "Abraham Maslow" },
  { text: "The ability to be in the present moment is a major component of mental wellness.", author: "Abraham Maslow" },
  { text: "Education is the movement from darkness to light.", author: "Allan Bloom" },
  { text: "The aim of education is to make a person capable of doing things, not just knowing them.", author: "John Henry Newman" },
  { text: "The test of a good teacher is not how many questions he can ask his pupils that they will answer readily, but how many questions he inspires them to ask him.", author: "Alice Wellington Rollins" },
  { text: "A teacher who can arouse a feeling for one single good action accomplishes more than he who fills our memory with rows on rows of natural objects.", author: "Johann Wolfgang von Goethe" },
  { text: "Knowing is not enough; we must apply. Willing is not enough; we must do.", author: "Johann Wolfgang von Goethe" },
  { text: "There is nothing more frightful than ignorance in action.", author: "Johann Wolfgang von Goethe" },
  { text: "We learn from history that we do not learn from history.", author: "Georg Wilhelm Friedrich Hegel" },
  { text: "Nothing great in the world was accomplished without passion.", author: "Georg Wilhelm Friedrich Hegel" },
  { text: "Truth is found neither in the thesis nor the antithesis, but in an emerging synthesis that reconciles the two.", author: "Georg Wilhelm Friedrich Hegel" },
  { text: "The only thing we learn from history is that we learn nothing from history.", author: "Georg Wilhelm Friedrich Hegel" },
  { text: "Be a student as long as you still have something to learn, and this will mean all your life.", author: "Henry L. Doherty" },
  { text: "The whole art of teaching is the art of awakening the natural curiosity of young minds.", author: "Anatole France" },
  { text: "To imagine is everything. It is the preview of life's coming attractions.", author: "Albert Einstein" },
  { text: "The most beautiful experience we can have is the mysterious. It is the fundamental emotion that stands at the cradle of true art and true science.", author: "Albert Einstein" },
  { text: "It is a miracle that curiosity survives formal education.", author: "Albert Einstein" },
  { text: "Weakness of attitude becomes weakness of character.", author: "Albert Einstein" },
  { text: "The only way to do great work is to love what you do. If you haven't found it yet, keep looking. Don't settle.", author: "Steve Jobs" },
  { text: "Your time is limited, so don't waste it living someone else's life.", author: "Steve Jobs" },
  { text: "Stay hungry, stay foolish.", author: "Steve Jobs" },
  { text: "The only way to be truly satisfied is to do what you believe is great work.", author: "Steve Jobs" },
  { text: "Creativity is just connecting things. When you ask creative people how they did something, they feel a little guilty because they didn't really do it, they just saw something.", author: "Steve Jobs" },
  { text: "The journey of a thousand miles begins with a single step.", author: "Lao Tzu" },
  { text: "Knowing others is intelligence; knowing yourself is true wisdom.", author: "Lao Tzu" },
  { text: "When the student is ready, the teacher will appear.", author: "Lao Tzu" },
  { text: "A good traveler has no fixed plans and is not intent on arriving.", author: "Lao Tzu" },
  { text: "At the center of your being you have the answer; you know who you are and what you want.", author: "Lao Tzu" },
  { text: "The key to growth is the introduction of higher dimensions of consciousness into our awareness.", author: "Lao Tzu" },
  { text: "By letting it go it all gets done. The world is won by those who let it go.", author: "Lao Tzu" },
  { text: "Nature does not hurry, yet everything is accomplished.", author: "Lao Tzu" },
  { text: "Mastering others is strength. Mastering yourself is true power.", author: "Lao Tzu" },
  { text: "To attain knowledge, add things every day. To attain wisdom, remove things every day.", author: "Lao Tzu" },
  { text: "Do the difficult things while they are easy and do the great things while they are small.", author: "Lao Tzu" },
  { text: "Silence is a source of great strength.", author: "Lao Tzu" },
  { text: "The sage does not hoard. The more he helps others, the more he benefits himself.", author: "Lao Tzu" },
  { text: "If you do not change direction, you may end up where you are heading.", author: "Lao Tzu" },
  { text: "New beginnings are often disguised as painful endings.", author: "Lao Tzu" },
  { text: "He who knows does not speak. He who speaks does not know.", author: "Lao Tzu" },
  { text: "The truth is not always beautiful, nor beautiful words the truth.", author: "Lao Tzu" },
  { text: "The softest things in the world overcome the hardest things in the world.", author: "Lao Tzu" },
  { text: "To see things in the seed, that is genius.", author: "Lao Tzu" },
  { text: "Anticipate the difficult by managing the easy.", author: "Lao Tzu" },
  { text: "The wise do not lay up their own treasures. The more they give to others, the more they have for their own.", author: "Lao Tzu" },
  { text: "The best student is not the one who memorizes facts, but the one who questions everything.", author: "Socrates" },
  { text: "Knowledge becomes wisdom only after it has been put to practical use.", author: "Aristotle" },
  { text: "Learning is a lifelong process of discovery, not a destination.", author: "John Dewey" },
  { text: "A curriculum that teaches students what to think rather than how to think fails at the first duty of education.", author: "Mortimer Adler" },
  { text: "The ultimate goal of the educational system is to shift to the individual the burden of pursuing his own education.", author: "John W. Gardner" },
  { text: "True education is learning to use the tools of learning.", author: "Dorothy Sayers" },
  { text: "Before you can teach a child, you must first reach the child.", author: "Booker T. Washington" },
  { text: "Nothing ever comes to one that is worth having except as a result of hard work.", author: "Booker T. Washington" },
  { text: "I have learned that success is to be measured not so much by the position that one has reached in life as by the obstacles which he has overcome.", author: "Booker T. Washington" },
  { text: "Associate yourself with people of good quality, for it is better to be alone than in bad company.", author: "Booker T. Washington" },
  { text: "The world cares very little about what a man or woman knows; it is what a man or woman is able to do that counts.", author: "Booker T. Washington" },
  { text: "Character is power.", author: "Booker T. Washington" },
  { text: "In any moment of decision, the best thing you can do is the right thing, the next best thing is the wrong thing, and the worst thing you can do is nothing.", author: "Theodore Roosevelt" },
  { text: "Do what you can, with what you have, where you are.", author: "Theodore Roosevelt" },
  { text: "The only man who never makes a mistake is the man who never does anything.", author: "Theodore Roosevelt" },
  { text: "Believe you can and you're halfway there.", author: "Theodore Roosevelt" },
  { text: "It is hard to fail, but it is worse never to have tried to succeed.", author: "Theodore Roosevelt" },
  { text: "Nobody cares how much you know, until they know how much you care.", author: "Theodore Roosevelt" },
  { text: "Far better it is to dare mighty things, to win glorious triumphs even though checkered by failure, than to rank with those poor spirits who neither enjoy nor suffer much.", author: "Theodore Roosevelt" },
  { text: "Knowing what's right doesn't mean much unless you do what's right.", author: "Theodore Roosevelt" },
  { text: "Comparison is the thief of joy.", author: "Theodore Roosevelt" },
  { text: "In the middle of difficulty lies opportunity.", author: "Albert Einstein" },
  { text: "The greatest minds are capable of the greatest vices as well as the greatest virtues.", author: "René Descartes" },
  { text: "The first step to knowledge is to know that we are ignorant.", author: "David Hume" },
  { text: "Beauty is no quality in things themselves: It exists merely in the mind which contemplates them.", author: "David Hume" },
  { text: "Reason is, and ought only to be the slave of the passions.", author: "David Hume" },
  { text: "A wise man proportions his belief to the evidence.", author: "David Hume" },
  { text: "The mind is a kind of theatre, where several perceptions successively make their appearance.", author: "David Hume" },
  { text: "No testimony is sufficient to establish a miracle, unless the testimony be of such a kind, that its falsehood would be more miraculous than the fact which it endeavors to establish.", author: "David Hume" },
  { text: "Reading furnishes the mind only with materials of knowledge; it is thinking that makes what we read ours.", author: "John Locke" },
  { text: "The improvement of understanding is for two ends: first, our own increase of knowledge; secondly, to enable us to deliver that knowledge to others.", author: "John Locke" },
  { text: "No man's knowledge here can go beyond his experience.", author: "John Locke" },
  { text: "What worries you, masters you.", author: "John Locke" },
  { text: "All wealth is the product of labor.", author: "John Locke" },
  { text: "The discipline of desire is the background of character.", author: "John Locke" },
  { text: "Things of this world are in so constant a flux, that nothing remains long in the same state.", author: "John Locke" },
  { text: "Men must be taught as if you taught them not, and things unknown proposed as things forgot.", author: "Alexander Pope" },
  { text: "A little learning is a dangerous thing; drink deep, or taste not the Pierian spring.", author: "Alexander Pope" },
  { text: "To err is human; to forgive, divine.", author: "Alexander Pope" },
  { text: "Hope springs eternal in the human breast.", author: "Alexander Pope" },
  { text: "Fools rush in where angels fear to tread.", author: "Alexander Pope" },
  { text: "For the things we have to learn before we can do them, we learn by doing them.", author: "Aristotle" },
  { text: "The intellectual is a person who thinks in terms of ideas, not things.", author: "Aristotle" },
  { text: "Those who know, do. Those that understand, teach.", author: "Aristotle" },
  { text: "The energy of the mind is the essence of life.", author: "Aristotle" },
  { text: "The high-minded man must care more for the truth than for what people think.", author: "Aristotle" },
  { text: "The one exclusive sign of thorough knowledge is the power of teaching.", author: "Aristotle" },
  { text: "All teaching and all intellectual learning come about from already existing knowledge.", author: "Aristotle" },
  { text: "He who cannot be a good follower cannot be a good leader.", author: "Aristotle" },
  { text: "Moral excellence comes about as a result of habit. We become just by doing just acts, temperate by doing temperate acts, brave by doing brave acts.", author: "Aristotle" },
  { text: "Wit is educated insolence.", author: "Aristotle" },
  { text: "The greatest of all masters is the instinct of imitation.", author: "Aristotle" },
  { text: "The soul never thinks without a picture.", author: "Aristotle" },
  { text: "Education is an ornament in prosperity and a refuge in adversity.", author: "Aristotle" },
  { text: "It is not once nor twice but times without number that the same ideas make their appearance in the world.", author: "Aristotle" },
  { text: "The wise man does not expose himself needlessly to danger.", author: "Aristotle" },
  { text: "Courage is the first of human qualities because it is the quality which guarantees the others.", author: "Aristotle" },
  { text: "To perceive is to suffer.", author: "Aristotle" },
  { text: "The education of the will is the object of our existence.", author: "Ralph Waldo Emerson" },
  { text: "The only gift is a portion of thyself.", author: "Ralph Waldo Emerson" },
  { text: "Make the most of yourself, for that is all there is of you.", author: "Ralph Waldo Emerson" },
  { text: "Nothing can bring you peace but yourself.", author: "Ralph Waldo Emerson" },
  { text: "The mind, once stretched by a new idea, never returns to its original dimensions.", author: "Ralph Waldo Emerson" },
  { text: "What lies behind us and what lies before us are tiny matters compared to what lies within us.", author: "Ralph Waldo Emerson" },
  { text: "For every minute you are angry you lose sixty seconds of happiness.", author: "Ralph Waldo Emerson" },
  { text: "The only person you are destined to become is the person you decide to be.", author: "Ralph Waldo Emerson" },
  { text: "Do not go where the path may lead, go instead where there is no path and leave a trail.", author: "Ralph Waldo Emerson" },
  { text: "Life is a succession of lessons which must be lived to be understood.", author: "Ralph Waldo Emerson" },
  { text: "Write it on your heart that every day is the best day in the year.", author: "Ralph Waldo Emerson" },
  { text: "Finish each day and be done with it. You have done what you could.", author: "Ralph Waldo Emerson" },
  { text: "To be great is to be misunderstood.", author: "Ralph Waldo Emerson" },
  { text: "Shallow men believe in luck. Strong men believe in cause and effect.", author: "Ralph Waldo Emerson" },
  { text: "We are what we repeatedly do. Excellence, then, is not an act, but a habit.", author: "Will Durant" },
  { text: "Knowledge is not skill. Knowledge plus ten thousand times is skill.", author: "Shinichi Suzuki" },
  { text: "The education of the heart is the education that truly matters.", author: "John Locke" },
  { text: "The foundation of every state is the education of its youth.", author: "Diogenes" },
  { text: "The purpose of education is to replace an empty mind with an open one.", author: "Malcolm Forbes" },
  { text: "The best way to become a better reader is to read more. The best way to become a better writer is to write more.", author: "Stephen King" },
  { text: "The most valuable resource that all teachers have is each other. Without collaboration our growth is limited to our own perspectives.", author: "Robert John Meehan" },
  { text: "Learning is not a spectator sport.", author: "Arthur W. Chickering" },
  { text: "The only real failure in life is not to be true to the best one knows.", author: "Buddha" },
]

export function getDailyQuote() {
  const now = new Date()
  const startOfYear = new Date(now.getFullYear(), 0, 0)
  const diff = now.getTime() - startOfYear.getTime()
  const dayOfYear = Math.floor(diff / 86400000)
  const index = dayOfYear % quotes.length
  return quotes[index]
}
