export { AboutModel } from "./about.model"
export type { IAbout } from "./about.model"
export { AssessmentModel } from "./assessment.model"
export type { IAssessment, IAssessmentScore } from "./assessment.model"
export { GradeColumnModel } from "./grade-column.model"
export type { IGradeColumn } from "./grade-column.model"
export { GradingSchemeModel } from "./grading-scheme.model"
export type { IGradingScheme, IGradingCategory, ISchemeComponent } from "./grading-scheme.model"
export { AnnouncementModel } from "./announcement.model"
export type { IAnnouncement } from "./announcement.model"
export { AuditLogModel } from "./audit-log.model"
export type { IAuditLog } from "./audit-log.model"
export { ClassStudentModel } from "./class-student.model"
export type { IClassStudent } from "./class-student.model"
export { CsoInfoModel } from "./cso-info.model"
export type { ICsoInfo } from "./cso-info.model"
export { CsoReportModel } from "./cso-report.model"
export type { ICsoReport } from "./cso-report.model"
export { GalleryItemModel } from "./gallery.model"
export type { IGalleryItem } from "./gallery.model"
export { DownloadableModel } from "./downloadable.model"
export type { IDownloadable } from "./downloadable.model"
export { GoverningDocumentModel } from "./governing-document.model"
export type { IGoverningDocument } from "./governing-document.model"
export { CurriculumModel } from "./curriculum.model"
export type { ICurriculum } from "./curriculum.model"
export { FacultyModel } from "./faculty.model"
export type { IFaculty } from "./faculty.model"
export { FeedbackModel } from "./feedback.model"
export type { IFeedback } from "./feedback.model"
export { GradeModel } from "./grade.model"
export type { IGrade } from "./grade.model"
export { NewsModel } from "./news.model"
export type { INews } from "./news.model"
export { OrgChartModel } from "./org-chart.model"
export type { IOrgChart } from "./org-chart.model"
export { QuickLinkModel } from "./quick-link.model"
export type { IQuickLink } from "./quick-link.model"
export { ScheduleModel } from "./schedule.model"
export type { ISchedule } from "./schedule.model"
export { SemesterModel } from "./semester.model"
export type { ISemester } from "./semester.model"
export { SeminarModel } from "./seminar.model"
export type { ISeminar } from "./seminar.model"
export { SubjectModel } from "./subject.model"
export type { ISubject } from "./subject.model"
export { ThesisModel } from "./thesis.model"
export type { IThesis } from "./thesis.model"
export { UserModel } from "./user.model"
export type { IUser } from "./user.model"
export { YearSectionModel } from "./year-section.model"
export type { IYearSection } from "./year-section.model"
export { ResetTokenModel } from "./reset-token.model"
export type { IResetToken } from "./reset-token.model"
